default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["PG_USERNAME"] %>
  password:

development:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>
  host: <%= ENV["PG_HOST"] %>

test:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>
  host: <%= ENV["PG_HOST"] %>

production:
  adapter: postgresql
  database: Falko-2017_2-BackEnd_production
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  url: <%= ENV["DATABASE_URL"] %>
  host: dokku.postgres.falko-database
